version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias (no hay ninguna en este caso)"
  build:
    commands:
      - echo "Construyendo proyecto (en este caso, nada que compilar)"
  post_build:
    commands:
      - echo "Fase post_build finalizada"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: .
